#!/bin/sh

## Thanks for HoracioEspinosa making this scripts, I edit it to work well under bash.
## https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716#gistcomment-3037288

branch="$(git rev-parse --abbrev-ref HEAD)";
commit_regex='((CDW-)([1-9][0-9])|((feat|fix|chore|refactor|style|test|docs)(((\w{0,15})))?))(:.\S.*)';
error_msg="Aborting commit. Your commit message format is invalid, please check the references."
commit_message="$1";

if ! grep -iqE "$commit_regex" < "${commit_message}"; then
echo "$error_msg" >&2
exit 1
fi

if [ "$branch" = "master" ]; then
echo "You can't commit directly to master branch"
exit 1
fi

if [ "$branch" = "develop" ]; then
echo "You can't commit directly to develop branch"
exit 1
fi
